name: Delivery API pipeline

on:
    push:
        branches:
            -main
    pull-request:
        branches:
            -main

jobs:
    security-sast:
        name: 0. SAST (Segurança)
        runs-on: ubuntu-latest
        steps:
            -name: checkout falhas e vulnerabilidades
            uses: ajinabraham/njsscan-action@master
            with:
                args: '.'

